"""initial schema

Revision ID: 47fc459cf334
Revises: 
Create Date: 2026-06-02 17:53:07.155539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47fc459cf334'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accent', sa.String(length=16), nullable=True),
    sa.Column('show_alert', sa.Boolean(), nullable=False),
    sa.Column('neg_threshold_m', sa.Numeric(), nullable=True),
    sa.Column('over_cap_warn', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balances_snapshot',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.Text(), nullable=True),
    sa.Column('account_kind', sa.String(length=16), nullable=True),
    sa.Column('balance_m', sa.Numeric(), nullable=False),
    sa.Column('balance_iqd_m', sa.Numeric(), nullable=False),
    sa.Column('last_active', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('snapshot_date', 'account_id', 'currency_id')
    )
    op.create_table('etl_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_max_date', sa.Date(), nullable=True),
    sa.Column('rows_loaded', sa.Integer(), nullable=False),
    sa.Column('usd_rate_used', sa.Numeric(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('opening_cash_m', sa.Numeric(), nullable=True),
    sa.Column('reconciliation_residual_m', sa.Numeric(), nullable=True),
    sa.Column('source_tz', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_base',
    sa.Column('series_key', sa.String(length=32), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('engine', sa.String(length=16), nullable=False),
    sa.Column('value_m', sa.Numeric(), nullable=False),
    sa.Column('cagr', sa.Numeric(), nullable=True),
    sa.Column('mape', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('series_key', 'year_month', 'engine')
    )
    op.create_table('installments_aging',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('bucket_key', sa.String(length=16), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('amount_m', sa.Numeric(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_date', 'bucket_key')
    )
    op.create_table('installments_summary',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('premium_count', sa.Integer(), nullable=False),
    sa.Column('face_total_m', sa.Numeric(), nullable=False),
    sa.Column('cash_paid_m', sa.Numeric(), nullable=False),
    sa.Column('discount_m', sa.Numeric(), nullable=False),
    sa.Column('remaining_m', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_date')
    )
    op.create_table('monthly_cashflow',
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('cash_in_m', sa.Numeric(), nullable=False),
    sa.Column('out_suppliers_m', sa.Numeric(), nullable=False),
    sa.Column('out_drawings_m', sa.Numeric(), nullable=False),
    sa.Column('out_refunds_m', sa.Numeric(), nullable=False),
    sa.Column('out_purchases_m', sa.Numeric(), nullable=False),
    sa.Column('out_salaries_m', sa.Numeric(), nullable=False),
    sa.Column('out_other_m', sa.Numeric(), nullable=False),
    sa.Column('out_siyrafa_m', sa.Numeric(), nullable=False),
    sa.Column('internal_transfers_m', sa.Numeric(), nullable=False),
    sa.Column('out_total_operational_m', sa.Numeric(), nullable=False),
    sa.Column('out_total_comprehensive_m', sa.Numeric(), nullable=False),
    sa.Column('net_operating_m', sa.Numeric(), nullable=False),
    sa.Column('net_total_m', sa.Numeric(), nullable=False),
    sa.Column('cash_running_m', sa.Numeric(), nullable=False),
    sa.Column('bond_count', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('year_month')
    )
    op.create_table('per_supplier_monthly',
    sa.Column('supplier_account_id', sa.Integer(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('paid_m', sa.Numeric(), nullable=False),
    sa.Column('paid_iqd_m', sa.Numeric(), nullable=False),
    sa.Column('paid_usd_m', sa.Numeric(), nullable=False),
    sa.Column('recv_m', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('supplier_account_id', 'year_month')
    )
    op.create_table('seasonal_index',
    sa.Column('series_key', sa.String(length=32), nullable=False),
    sa.Column('fm_pos', sa.Integer(), nullable=False),
    sa.Column('avg_value_m', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('series_key', 'fm_pos')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('related_key', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('before_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_key', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_caps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('monthly_cap_m', sa.Numeric(), nullable=False),
    sa.Column('plan_low_m', sa.Numeric(), nullable=False),
    sa.Column('plan_high_m', sa.Numeric(), nullable=False),
    sa.Column('user_monthly_m', sa.Numeric(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('usd_rate', sa.Numeric(), nullable=True),
    sa.Column('unexpected_reserve_m', sa.Numeric(), nullable=True),
    sa.Column('income_growth_pct', sa.Numeric(), nullable=True),
    sa.Column('in_growth_factor', sa.Numeric(), nullable=True),
    sa.Column('out_growth_factor', sa.Numeric(), nullable=True),
    sa.Column('cagr_floor', sa.Numeric(), nullable=True),
    sa.Column('cagr_cap', sa.Numeric(), nullable=True),
    sa.Column('forecast_horizon', sa.Integer(), nullable=True),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=True),
    sa.Column('forecast_engine', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_assumptions_global', 'assumptions', [sa.literal_column('(scenario_id IS NULL)')], unique=True, postgresql_where=sa.text('scenario_id IS NULL'), sqlite_where=sa.text('scenario_id IS NULL'))
    op.create_index('uq_assumptions_per_scenario', 'assumptions', ['scenario_id'], unique=True, postgresql_where=sa.text('scenario_id IS NOT NULL'), sqlite_where=sa.text('scenario_id IS NOT NULL'))
    op.create_table('payment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('pool_for_suppliers_m', sa.Numeric(), nullable=False),
    sa.Column('reserve_m', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_month', 'scenario_id', name='uq_plan_month_scenario')
    )
    op.create_table('scenario_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('series_key', sa.String(length=32), nullable=False),
    sa.Column('adjust_pct', sa.Numeric(), nullable=True),
    sa.Column('override_value_m', sa.Numeric(), nullable=True),
    sa.Column('year_month', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_plan_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_plan_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('planned_m', sa.Numeric(), nullable=False),
    sa.Column('cap_applied_m', sa.Numeric(), nullable=False),
    sa.Column('allocated_m', sa.Numeric(), nullable=False),
    sa.Column('actual_paid_m', sa.Numeric(), nullable=False),
    sa.Column('variance_m', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['payment_plan_id'], ['payment_plans.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_plan_lines')
    op.drop_table('scenario_adjustments')
    op.drop_table('payment_plans')
    op.drop_index('uq_assumptions_per_scenario', table_name='assumptions', postgresql_where=sa.text('scenario_id IS NOT NULL'), sqlite_where=sa.text('scenario_id IS NOT NULL'))
    op.drop_index('uq_assumptions_global', table_name='assumptions', postgresql_where=sa.text('scenario_id IS NULL'), sqlite_where=sa.text('scenario_id IS NULL'))
    op.drop_table('assumptions')
    op.drop_table('supplier_caps')
    op.drop_table('scenarios')
    op.drop_table('notes')
    op.drop_table('audit_log')
    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('seasonal_index')
    op.drop_table('per_supplier_monthly')
    op.drop_table('monthly_cashflow')
    op.drop_table('installments_summary')
    op.drop_table('installments_aging')
    op.drop_table('forecast_base')
    op.drop_table('etl_runs')
    op.drop_table('balances_snapshot')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
