"""schema hardening: uniqueness constraints

Revision ID: 67f6cf4a71f8
Revises: 47fc459cf334
Create Date: 2026-06-05 00:52:12.079318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f6cf4a71f8'
down_revision: Union[str, Sequence[str], None] = '47fc459cf334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_plan_line_supplier', 'payment_plan_lines', ['payment_plan_id', 'supplier_id'])
    op.create_unique_constraint('uq_scenario_adj', 'scenario_adjustments', ['scenario_id', 'series_key', 'year_month'])
    op.create_index('uq_scenario_adj_all_months', 'scenario_adjustments', ['scenario_id', 'series_key'], unique=True, postgresql_where=sa.text('year_month IS NULL'), sqlite_where=sa.text('year_month IS NULL'))
    op.create_index('uq_one_baseline_scenario', 'scenarios', ['is_baseline'], unique=True, postgresql_where=sa.text('is_baseline'), sqlite_where=sa.text('is_baseline = 1'))
    op.create_unique_constraint('uq_supplier_cap_effective', 'supplier_caps', ['supplier_id', 'effective_from'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_supplier_cap_effective', 'supplier_caps', type_='unique')
    op.drop_index('uq_one_baseline_scenario', table_name='scenarios', postgresql_where=sa.text('is_baseline'), sqlite_where=sa.text('is_baseline = 1'))
    op.drop_index('uq_scenario_adj_all_months', table_name='scenario_adjustments', postgresql_where=sa.text('year_month IS NULL'), sqlite_where=sa.text('year_month IS NULL'))
    op.drop_constraint('uq_scenario_adj', 'scenario_adjustments', type_='unique')
    op.drop_constraint('uq_plan_line_supplier', 'payment_plan_lines', type_='unique')
    # ### end Alembic commands ###
